version: "3.9"

services:
  postgres-db:
    image: postgres:17.2
    restart: always
    ports:
      - 6000:5432
    environment:
      POSTGRES_PASSWORD: ryans_pass
      POSTGRES_USER: ryan

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:9090"
    environment:
      PG_USER: ryan
      PG_PASSWORD: ryans_pass
      PG_HOST: postgres-db
      PG_PORT: 5432
      PG_DB: postgres
      S3_ACCESS_SECRET:
      S3_KEY:
      S3_REGION: eu-north-1
      S3_BUCKET: pix-pursuit
